name: Rust Checks

on: [push, pull_request]

jobs:
  rust-lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check formatting with Rustfmt
        run: |
          cd src-tauri
          cargo fmt -- --check

      - name: Check linting with Clippy
        run: |
          cd src-tauri
          cargo clippy -- -D warnings

      - name: Build with Cargo
        run: |
          cd src-tauri
          cargo build --release
